#! /bin/sh

sxhkd &

bspc monitor DisplayPort-0 -d I II III IV V 
bspc monitor DisplayPort-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding		30

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

$HOME/.config/polybar/launch.sh
