#! /bin/sh

sxhkd &

FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
BLACK8=$(xrdb -query | grep 'color8:' | awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
RED9=$(xrdb -query | grep 'color9:' | awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
GREEN10=$(xrdb -query | grep 'color10:' | awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
YELLOW11=$(xrdb -query | grep 'color11:' | awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
BLUE12=$(xrdb -query | grep 'color12:' | awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
MAGENTA13=$(xrdb -query | grep 'color13:' | awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
CYAN14=$(xrdb -query | grep 'color14:' | awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
WHITE15=$(xrdb -query | grep 'color15:' | awk '{print $NF}')

bspc monitor -d I II III IV V

bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 36.5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config focused_border_color "$YELLOW11"
bspc config normal_border_color "$WHITE"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc rule -a Zathura state=tiled
$HOME/.config/polybar/launch.sh
