#! /bin/sh

sxhkd &

FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color8:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')

bspc monitor -d I II III IV V

bspc config border_width         6
bspc config window_gap           14
bspc config top_padding		       50

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

bspc config focused_border_color        "$BLUE" 
bspc config normal_border_color         "$BLACK"
bspc config active_border_color         "$MAGENTA"
bspc config presel_feedback_color       "$GREEN"

bspc rule -a Zathura state=tiled
$HOME/.config/polybar/launch.sh
